USE indieheads;

-- DROP TABLE EQUIPMENTVENDOR;

CREATE TABLE EQUIPMENTVENDOR (
    EquipmentVendor_ID INT AUTO_INCREMENT PRIMARY KEY,
    Equipment_ID INT,
    Vendor_ID INT,
    FOREIGN KEY (Equipment_ID) REFERENCES EQUIPMENT(Equipment_ID),
    FOREIGN KEY (Vendor_ID) REFERENCES VENDOR(Vendor_ID)
);