USE indieheads;

-- DROP TABLE EVENTEQUIPMENT;

CREATE TABLE EVENTEQUIPMENT (
    EventEquipment_ID INT AUTO_INCREMENT PRIMARY KEY,
    Event_ID INT,
    Equipment_ID INT,
    FOREIGN KEY (Event_ID) REFERENCES EVENT(Event_ID),
    FOREIGN KEY (Equipment_ID) REFERENCES EQUIPMENT(Equipment_ID)
);