USE indieheads;

-- DROP TABLE MERCHVENDOR;

CREATE TABLE MERCHVENDOR (
    MerchVendor_ID INT AUTO_INCREMENT PRIMARY KEY,
    Merch_ID INT,
    Vendor_ID INT,
    QuantitySupplied INT,
    FOREIGN KEY (Merch_ID) REFERENCES MERCH(Merch_ID),
    FOREIGN KEY (Vendor_ID) REFERENCES VENDOR(Vendor_ID)
);