SELECT * FROM BANDS;

SELECT * FROM VOLUNTEER;

SELECT E.*, V.Volunteer_FName, V.Volunteer_LName
FROM EQUIPMENT E
LEFT JOIN VOLUNTEER V ON E.Volunteer_ID = V.Volunteer_ID;

SELECT * FROM MERCH;

SELECT * FROM VENDOR;

SELECT * FROM VENUE;

SELECT EV.*, E.Equipment_Type, V.Vendor_Name
FROM EQUIPMENTVENDOR EV
INNER JOIN EQUIPMENT E ON EV.Equipment_ID = E.Equipment_ID
INNER JOIN VENDOR V ON EV.Vendor_ID = V.Vendor_ID;

SELECT * FROM EVENT;

SELECT EE.*, E.Event_Date, E.Event_Time, EQ.Equipment_Type
FROM EVENTEQUIPMENT EE
INNER JOIN EVENT E ON EE.Event_ID = E.Event_ID
INNER JOIN EQUIPMENT EQ ON EE.Equipment_ID = EQ.Equipment_ID;

SELECT EM.*, E.Event_Date, E.Event_Time, M.Merch_Type
FROM EVENTMERCH EM
INNER JOIN EVENT E ON EM.Event_ID = E.Event_ID
INNER JOIN MERCH M ON EM.Merch_ID = M.Merch_ID;

SELECT MV.*, M.Merch_Type, V.Vendor_Name
FROM MERCHVENDOR MV
INNER JOIN MERCH M ON MV.Merch_ID = M.Merch_ID
INNER JOIN VENDOR V ON MV.Vendor_ID = V.Vendor_ID;

SELECT 
    SETLIST.Set_ID, SETLIST.Event_ID, EVENT.Event_Date,
    SETLIST.Band_ID, BANDS.Band_Name, SETLIST.Timeslot
FROM 
    SETLIST
LEFT JOIN 
    EVENT ON SETLIST.Event_ID = EVENT.Event_ID
LEFT JOIN 
    BANDS ON SETLIST.Band_ID = BANDS.Band_ID;

SELECT 
    VOLUNTEERSCHEDULE.VolunteerSchedule_ID, VOLUNTEERSCHEDULE.Event_ID, EVENT.Event_Date,
    VOLUNTEERSCHEDULE.Volunteer_ID, VOLUNTEER.Volunteer_FName, VOLUNTEERSCHEDULE.Timeslot
FROM 
    VOLUNTEERSCHEDULE
LEFT JOIN 
    EVENT ON VOLUNTEERSCHEDULE.Event_ID = EVENT.Event_ID
LEFT JOIN 
    VOLUNTEER ON VOLUNTEERSCHEDULE.Volunteer_ID = VOLUNTEER.Volunteer_ID;
