USE indieheads;

-- DROP TABLE IF EXISTS EVENTEQUIPMENT;

CREATE TABLE EVENTEQUIPMENT (
    EventEquipment_ID INT AUTO_INCREMENT PRIMARY KEY,
    Event_ID INT,
    Equipment_ID INT,
    FOREIGN KEY (Event_ID) REFERENCES EVENT(Event_ID),
    FOREIGN KEY (Equipment_ID) REFERENCES EQUIPMENT(Equipment_ID)
);

INSERT INTO EVENTEQUIPMENT (Event_ID, Equipment_ID) 
VALUES 
(1, 3), 
(1, 5),
(1, 7);

INSERT INTO EVENTEQUIPMENT (Event_ID, Equipment_ID) 
VALUES 
(1, 1), 
(1, 4),
(1, 7);
